// Open XML SDK usings only — keep this file free of iText7 using directives
// to avoid CS0104 ambiguous-reference errors (Paragraph, Document, Path, Table, Text, etc.)
using DocumentFormat.OpenXml;
using DocumentFormat.OpenXml.Packaging;
using OxmlWordprocessing = DocumentFormat.OpenXml.Wordprocessing;

namespace DocumentParser.Generators;

/// <summary>
/// Generates a multi-section DOCX with explicit page breaks and a table.
/// Uses alias <c>OxmlWordprocessing</c> internally; callers never see iText7 types here.
/// </summary>
internal static class DocxSampleGenerator
{
    internal static void Generate(string path)
    {
        using var wordDoc = WordprocessingDocument.Create(
            path, WordprocessingDocumentType.Document);

        var mainPart = wordDoc.AddMainDocumentPart();
        mainPart.Document = new OxmlWordprocessing.Document();
        var body = mainPart.Document.AppendChild(new OxmlWordprocessing.Body());

        // ── Page 1 ──────────────────────────────────────────────────────────
        AppendHeading(body, "Section 1 — Introduction (Page 1)");
        AppendParagraph(body,
            "This DOCX file is generated by Open XML SDK to serve as a test fixture. " +
            "DocxParser reads paragraphs and tables, splits on explicit page breaks, " +
            "and tracks the current page number for each text segment.");

        AppendParagraph(body,
            "Product list below is stored as a table. Cell text is extracted row-by-row, " +
            "separated by ' | '.");

        AppendTable(body, new[,]
        {
            { "Product Name",  "Category",    "Price"    },
            { "Widget Alpha",  "Electronics", "$29.99"   },
            { "Gadget Beta",   "Tools",       "$49.50"   },
            { "Module Gamma",  "Software",    "$199.00"  },
        });

        AppendExplicitPageBreak(body);

        // ── Page 2 ──────────────────────────────────────────────────────────
        AppendHeading(body, "Section 2 — Details (Page 2)");
        AppendParagraph(body,
            "This paragraph is on page 2 — separated from page 1 by an explicit " +
            "<w:pageBreak/> element. DocxParser increments the page counter on that break.");
        AppendParagraph(body,
            "LIMITATION: Without explicit breaks, Open XML SDK cannot determine page " +
            "boundaries. The SDK is a structural reader, not a rendering engine.");

        AppendExplicitPageBreak(body);

        // ── Page 3 ──────────────────────────────────────────────────────────
        AppendHeading(body, "Section 3 — Conclusion (Page 3)");
        AppendParagraph(body,
            "Page 3 content. This section concludes the sample DOCX document. " +
            "Headers, footers, footnotes, and text boxes are NOT extracted by DocxParser.");

        // OOXML spec requires a final empty paragraph in body.
        body.AppendChild(new OxmlWordprocessing.Paragraph());

        mainPart.Document.Save();
    }

    // ── OOXML element builders ─────────────────────────────────────────────

    private static void AppendHeading(OxmlWordprocessing.Body body, string text)
    {
        var para = new OxmlWordprocessing.Paragraph(
            new OxmlWordprocessing.Run(
                new OxmlWordprocessing.RunProperties(new OxmlWordprocessing.Bold()),
                new OxmlWordprocessing.Text(text)
            )
        );
        body.AppendChild(para);
    }

    private static void AppendParagraph(OxmlWordprocessing.Body body, string text)
    {
        body.AppendChild(new OxmlWordprocessing.Paragraph(
            new OxmlWordprocessing.Run(new OxmlWordprocessing.Text(text))
        ));
    }

    private static void AppendExplicitPageBreak(OxmlWordprocessing.Body body)
    {
        body.AppendChild(new OxmlWordprocessing.Paragraph(
            new OxmlWordprocessing.Run(
                new OxmlWordprocessing.Break { Type = OxmlWordprocessing.BreakValues.Page })
        ));
    }

    private static void AppendTable(OxmlWordprocessing.Body body, string[,] data)
    {
        var table = new OxmlWordprocessing.Table();

        var tblPr = new OxmlWordprocessing.TableProperties(
            new OxmlWordprocessing.TableBorders(
                new OxmlWordprocessing.TopBorder    { Val = OxmlWordprocessing.BorderValues.Single, Size = 4 },
                new OxmlWordprocessing.BottomBorder { Val = OxmlWordprocessing.BorderValues.Single, Size = 4 },
                new OxmlWordprocessing.LeftBorder   { Val = OxmlWordprocessing.BorderValues.Single, Size = 4 },
                new OxmlWordprocessing.RightBorder  { Val = OxmlWordprocessing.BorderValues.Single, Size = 4 },
                new OxmlWordprocessing.InsideHorizontalBorder { Val = OxmlWordprocessing.BorderValues.Single, Size = 4 },
                new OxmlWordprocessing.InsideVerticalBorder   { Val = OxmlWordprocessing.BorderValues.Single, Size = 4 }
            )
        );
        table.AppendChild(tblPr);

        int rows = data.GetLength(0);
        int cols = data.GetLength(1);

        for (int r = 0; r < rows; r++)
        {
            var row = new OxmlWordprocessing.TableRow();
            for (int c = 0; c < cols; c++)
            {
                var runPr = r == 0
                    ? new OxmlWordprocessing.RunProperties(new OxmlWordprocessing.Bold())
                    : new OxmlWordprocessing.RunProperties();

                var cell = new OxmlWordprocessing.TableCell(
                    new OxmlWordprocessing.Paragraph(
                        new OxmlWordprocessing.Run(
                            runPr,
                            new OxmlWordprocessing.Text(data[r, c])
                        )
                    )
                );
                row.AppendChild(cell);
            }
            table.AppendChild(row);
        }

        body.AppendChild(table);
    }
}
