// iText7 usings only — keep this file free of Open XML SDK using directives
// to avoid CS0104 ambiguous-reference errors (Paragraph, Document, Path, Table, etc.)
using iText.IO.Font.Constants;
using iText.Kernel.Font;
using iText.Kernel.Geom;
using iText.Kernel.Pdf;
using iText.Kernel.Pdf.Canvas;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;

namespace DocumentParser.Generators;

/// <summary>Generates three sample PDF files for parsing tests.</summary>
internal static class PdfSampleGenerator
{
    // iText7 9.x: PdfFont instances are bound to the PdfDocument they belong to.
    // Never share font instances across documents — create fresh inside each method.

    // ── Sample 1: single page, plain text ────────────────────────────────────

    internal static void GenerateTextPdf(string path)
    {
        using var writer = new PdfWriter(path);
        using var pdfDoc = new PdfDocument(writer);
        using var doc = new Document(pdfDoc);

        // Create fonts inside the document scope.
        var bold    = PdfFontFactory.CreateFont(StandardFonts.HELVETICA_BOLD);
        var regular = PdfFontFactory.CreateFont(StandardFonts.HELVETICA);
        var oblique = PdfFontFactory.CreateFont(StandardFonts.HELVETICA_OBLIQUE);

        doc.Add(new Paragraph("Sample PDF 1 — Plain Text")
            .SetFont(bold).SetFontSize(18));

        doc.Add(new Paragraph(
            "This is a single-page, text-based PDF generated by iText7. " +
            "iText7's SimpleTextExtractionStrategy extracts this text cleanly " +
            "and returns it as Page 1.")
            .SetFont(regular).SetFontSize(12));

        doc.Add(new Paragraph(
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. " +
            "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. " +
            "Ut enim ad minim veniam, quis nostrud exercitation ullamco.")
            .SetFont(regular).SetFontSize(11));

        doc.Add(new Paragraph(
            $"Generated at: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC")
            .SetFont(oblique).SetFontSize(9));
    }

    // ── Sample 2: 3 pages with distinct per-page content ─────────────────────

    internal static void GenerateMultiPagePdf(string path)
    {
        using var writer = new PdfWriter(path);
        using var pdfDoc = new PdfDocument(writer);
        using var doc = new Document(pdfDoc);

        var bold    = PdfFontFactory.CreateFont(StandardFonts.HELVETICA_BOLD);
        var regular = PdfFontFactory.CreateFont(StandardFonts.HELVETICA);

        for (int pageNum = 1; pageNum <= 3; pageNum++)
        {
            if (pageNum > 1)
                doc.Add(new AreaBreak(AreaBreakType.NEXT_PAGE));

            doc.Add(new Paragraph($"Page {pageNum} of 3 — Multi-Page PDF")
                .SetFont(bold).SetFontSize(16));

            doc.Add(new Paragraph(
                $"Content of page {pageNum}. Each page has a distinct heading so the parser " +
                $"can be verified to attribute text to the correct page number (1-based: {pageNum}).")
                .SetFont(regular).SetFontSize(11));

            doc.Add(new Paragraph(
                $"Product on page {pageNum}: Widget-{pageNum * 100}, " +
                $"Category: Electronics, Price: ${pageNum * 29.99m:F2}")
                .SetFont(regular).SetFontSize(10));
        }
    }

    // ── Sample 3: simulated scanned PDF ──────────────────────────────────────
    // Page 1 has NO Unicode text stream (only canvas drawing) — models a scanned page.
    // Page 2 has a real text layer — models a mixed document.

    internal static void GenerateScannedSimPdf(string path)
    {
        using var writer = new PdfWriter(path);
        using var pdfDoc = new PdfDocument(writer);

        // Page 1 — draw-only, no text content stream.
        var page1 = pdfDoc.AddNewPage(PageSize.A4);
        var canvas1 = new PdfCanvas(page1);
        canvas1.SetFillColorGray(0.92f)
               .Rectangle(50, 100, 495, 692)
               .Fill();
        // No BeginText/EndText — iText7 extractor returns empty string for this page.

        // Page 2 — real text layer.
        var page2 = pdfDoc.AddNewPage(PageSize.A4);
        var canvas2 = new PdfCanvas(page2);
        var font = PdfFontFactory.CreateFont();
        canvas2.BeginText()
               .SetFontAndSize(font, 14)
               .MoveText(72, 750)
               .ShowText("Page 2 — Text layer present")
               .MoveText(0, -30)
               .SetFontAndSize(font, 11)
               .ShowText("This page has a real text layer. Page 1 simulates a scanned image page.")
               .MoveText(0, -20)
               .ShowText("iText7 returns empty string for page 1; this text is extracted normally.")
               .EndText();
    }
}
